### ISSUE TITLE
Play with PC-keyboard

### ISSUE THREAD

**Issue by vad0s94** [thestr4ng3r/chiaki#155]
Is it possible to use Gamepad emulators on my Windows to play with keyboard? 
Or real dualshock 4 is required?

**Comment by danwdart** [comment]
Shortcuts exist to press buttons with keyboard in settings.

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.

**Comment by thestr4ng3r** [comment]
Yes, this was fixed in #174
