### ISSUE TITLE
Send input with Chiaki library

### ISSUE THREAD

**Issue by interdpth** [thestr4ng3r/chiaki#164]
Hi, 
Chiaki seems to be able to just send input with no timing issues, but when I use chiaki_session_set_controller_state via the library if I do not add a thread.sleep I am not guaranteed the input. However with a thread.sleep, my input isn't always the best timed. I tried locking the state/gamepad mutexes and waiting for those but that was no help. Is there an event I'm missing to signify the control input sent? Thanks for the great tool.

**Comment by thestr4ng3r** [comment]
It depends on where your input comes from. Normally you only want to call `chiaki_session_set_controller_state()` when you really receive a controller event whatever gives you input.

**Comment by interdpth** [comment]
Say I have a script to test somethings.

It sends 5 different chiaki_session_set_controller_state() in a row. When this happens only the fifth input gets sent. 

I did noticed you were looking into putting in 200 ms timeout. Just looking for options on how to do this.

Thanks!

**Comment by thestr4ng3r** [comment]
The `FEEDBACK_STATE_TIMEOUT_MAX_MS` is for continuously sending a packet every 200 ms if NO `chiaki_session_set_controller_state()` calls happen.

What can happen if you do the calls directly after each other is that the state gets updated 5 times and the condition variable gets signaled after each update, however the sending thread is woken up only after the last time, so only the last state is taken into account.
This may or may not be considered to be a bug. Basically it means if input comes faster than the kernel schedules, intermediate states will be dropped, which might not be too bad since the final state will be sent correctly.
It could be solved by putting the states into a queue and handling it then in the sending thread.

But depending on what you are trying to achieve, sleeping between inputs may also not be a bad solution. After all, you are simulating input to the PS4 that normally comes from a user, which would be slower too.

**Comment by interdpth** [comment]
Thanks, I'll close this out.
