### ISSUE TITLE
Chiaki.pdb - Not found (Debugged with Microsoft VS)

### ISSUE THREAD

**Issue by xXSkyWalkerXx1** [thestr4ng3r/chiaki#188]
**Hey guys,**

previous I have already opened a thread, sadly without any response.
I have debugged Chiaki now with Microsoft-Visual Studios and here's the window:

![Screenshot - 12_03](https://user-images.githubusercontent.com/61758775/76558198-27499c00-649d-11ea-8fef-fd2dc17c1624.png)

![Screenshot - 12_03 002](https://user-images.githubusercontent.com/61758775/76558205-29abf600-649d-11ea-893b-09abba86d83d.png)

![Screenshot - 12_03 003](https://user-images.githubusercontent.com/61758775/76558211-2c0e5000-649d-11ea-96dd-4ce0388ba6e6.png)

**So, how can I fix that???**
I hope now to get any help now. xD
I think I need only the chiaki.pdb file?

**Best regards,**
_xXSkyWalkerXx1_

**Comment by LiuBiCai** [comment]
I'm sad to tell you that. You can't do that. Because the code was built in linux. So you can't debug in windows. If you want debug, you should use linux

**Comment by xXSkyWalkerXx1** [comment]
> I'm sad to tell you that. You can't do that. Because the code was built in linux. So you can't debug in windows. If you want debug, you should use linux

Else, do you know what I can do?
I'm just getting a black screen after connecting to my PS4 and the log file says:
https://user-images.githubusercontent.com/61758775/75816311-4194c300-5d95-11ea-843f-2666b6ff8a18.png

**Comment by thestr4ng3r** [comment]
> I'm sad to tell you that. You can't do that. Because the code was built in linux. So you can't debug in windows. If you want debug, you should use linux

This isn't really correct, the Windows builds are built on AppVeyor with MSVC. You can very well debug under Windows, it's just kind of a pain because Windows is a crappy development environment overall.

If you really want to debug the official builds, PDBs are automatically pushed as AppVeyor artifacts, for 1.1.3 for example: https://ci.appveyor.com/project/thestr4ng3r/chiaki/builds/30389727/artifacts
But usually if you want to debug something, it's better to just built it yourself.
