### ISSUE TITLE
.deb packages

### ISSUE THREAD

**Issue by mhalano** [thestr4ng3r/chiaki#204]
Would be nice to have code in place or even a PPA where we can get official .deb packages. I think a Snap os better because the auto-update feature, but .deb is quite a standard these days.

**Comment by fenio** [comment]
I started working on official Debian package but first thing that will be blocker are third-party libraries.
Debian has already packages for gf-complete, jerasure and nanopb but chiaki builds their own during compilation and I didn't find a way to disable it and force using system wide versions. Is there a switch for cmake to do so?
One of requirement for Debian is to use existing packages as a build dependency.

@thestr4ng3r thoughts?

Is it possible to first look for existing libraries and fallback to build own only if they are absent?

**Comment by thestr4ng3r** [comment]
Currently there is no such switch but it should be easy to add it if the system dependencies are sufficient for chiaki. What oldest debian version are you planning to package it for?
Would be cool to have that before the MiniDebConf.

**Comment by fenio** [comment]
Well in general when you packages something for Debian you're aiming at Sid/unstable. But once we've got working package we can try to backport it to older releases like bullseye(testing) or buster(stable). But so far I checked just sid/unstable for dependencies. Not sure if all of them are already available also in testing/stable.

**Comment by fenio** [comment]
https://wiki.debian.org/DebianEvents/internet/2020/MiniDebConfOnline2 that MiniDebConf?

**Comment by fenio** [comment]
Ok I can see you're register for it so that's the correct MiniDebConf.
Well you have to know that once package is prepared and uploaded for the first time it goes to NEW queue and it takes some time before ftp-masters approve it. They usually have some backlog... https://ftp-master.debian.org/new.html
But we can create some PPA or just share link do package once it's ready.
Even announcing that package is already in NEW queue will be cool during DebConf ;)

**Comment by fenio** [comment]
For the record this is Debian's bugreport for this effort.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949550

**Comment by fenio** [comment]
Anyway. I'm not really familiar with CMake so if we want to push it forward quickly then I need help with that. I can try to do it myself but I'm pretty sure that it will be much easier for someone familiar with CMake so I don't really want to spend time on this. I'd prefer to spend time on things I'm familiar with which is Debian stuff.
@thestr4ng3r can you prepare version of chiaki that would look for system wide libraries first?
Can be just patch/diff for my own purposes for now.

**Comment by thestr4ng3r** [comment]
Yes, I'm working on it: #347

**Comment by fenio** [comment]
Any chance for similar changes for rest of 3rd party libs?
Are you going to work on them too?

**Comment by thestr4ng3r** [comment]
Yes, thanks for the reminder.

**Comment by thestr4ng3r** [comment]
@fenio jerasure, gf-complete and nanopb can now be used from the system. I've also added a CI job for bullseye to test this: https://github.com/thestr4ng3r/chiaki/blob/master/.github/workflows/bullseye.yml
By default, the build system first tries to use the system libraries and if not found falls back to the submodules.
You can force it to use the system libraries and error if not found by passing `-DCHIAKI_USE_SYSTEM_JERASURE=ON -DCHIAKI_USE_SYSTEM_NANOPB=ON` to cmake.
Anything else you need?

**Comment by fenio** [comment]
Nope. I should be good to start now. Thanks for robust response. Will share results of my efforts soon ;)

**Comment by fenio** [comment]
Now it failed because of lack of munit which AFAICS is not part of Debian.
For now I will disable tests by -DCHIAKI_ENABLE_TESTS=OFF.
Will think what do to with that later.

**Comment by fenio** [comment]
Ok we've got first legal issue. As you probably know Debian is quite strict with regards to that ;)

E: possible-gpl-code-linked-with-openssl
N:
N:   This package appears to be covered by the GNU GPL but depends on the
N:   OpenSSL libssl package and does not mention a license exemption or
N:   exception for OpenSSL in its copyright file. The GPL (including
N:   version 3) is incompatible with some terms of the OpenSSL license, and
N:   therefore Debian does not allow GPL-licensed code linked with OpenSSL
N:   libraries unless there is a license exception explicitly permitting
N:   this.

https://www.openssl.org/docs/faq.html#LEGAL2
Are you willing to add such exemption to your code?

**Comment by thestr4ng3r** [comment]
Yes, this exemption seems sensible, I've added it to the readme for now. All the code files also contain the typical GPL header, do you need it to be stated there as well? Also do you need a new release for this?

**Comment by fenio** [comment]
I've just checked few other packages and I think that every file which is part of final binary linked to OpenSSL should have it also in header. At least that's my understanding after reading debian/copyright for similar programs:

 In addition, as a special exception, the copyright holders give
 permission to link the code of portions of this program with the
 OpenSSL library under certain conditions as described in each
 individual source file, and distribute linked combinations including
 the two.

And at this point I don't need new release for all these changes. I'm downloading copy of the repo and for now I call it version 1.3.0+commit-hash.

**Comment by thestr4ng3r** [comment]
Ok, since then the comments would get quite long, I would like to use standard SPDX headers instead: https://github.com/thestr4ng3r/chiaki/pull/354
Unfortunately there is only this OpenVPN-specific exception for OpenSSL officially registered with SPDX: https://spdx.org/licenses/openvpn-openssl-exception.html and I didn't find any way to use https://spdx.org/licenses/GPL-3.0-linking-source-exception.html specifying the template arguments, so I had to use LicenseRef.
Let me know if this is acceptable for you.

**Comment by fenio** [comment]
Well first of all it's not me who has such strict requirements. It's the Debian project. For me just mentioning that exception even just in README is just fine. I'm just not sure if it is enough for ftp-masters who approve new packages into Debian. If they have concerns they usually ask debian-legal mailinglist which is full of folks much more involved in legal / law / copyrights stuff. I'm not an expert in that area. All I could do is to provide you examples of other packages with such exception (mosh, openvpn).
I know it sounds awkward but I won't be the one accepting package into Debian archive. I will be just uploader. 
We can try to upload whatever we / you find easier. I just can't guarantee it will be accepted. And if it won't be accepted then it mans delays.

Back to the business. I've got working package which just needs some minor polishing. Once we decide what do we do with that OpenSSL crap I can start preparing official upload :)

Thanks a lot for your robust answers and actions. I know that Debian isn't the easiest partner on the world.

**Comment by thestr4ng3r** [comment]
> Well first of all it's not me who has such strict requirements. It's the Debian project. For me just mentioning that exception even just in README is just fine. I'm just not sure if it is enough for ftp-masters who approve new packages into Debian. If they have concerns they usually ask debian-legal mailinglist which is full of folks much more involved in legal / law / copyrights stuff. I'm not an expert in that area. All I could do is to provide you examples of other packages with such exception (mosh, openvpn).
> I know it sounds awkward but I won't be the one accepting package into Debian archive. I will be just uploader.
> We can try to upload whatever we / you find easier. I just can't guarantee it will be accepted. And if it won't be accepted then it mans delays.

Yes, that is what I meant too. I guess my formalization was a bit incorrect.

> Back to the business. I've got working package which just needs some minor polishing. Once we decide what do we do with that OpenSSL crap I can start preparing official upload :)

Sounds good! I have merged the SPDX header changes, which I hope will be accepted then.

**Comment by fenio** [comment]
Fingers crossed. Since AFAIR you merged also some CLI streaming changes maybe releasing 1.3.1 is not the worst idea.
You can call it DebConfRelease... you know social engineering and stuff like that to convince ftp masters to accept package :)

Also I will try to prepare manual page for chiaki. It's not really requirement but if we will have 0 lintian warnings it simply looks better than some warnings / errors. Lintian is package checker if you don't know that tool.

**Comment by fenio** [comment]
So package is ready... almost. It builds fine on my laptop so I started testing builds in cowbuilder/pbuilder (basically just wrapper around chroot command) to see if all dependencies are ok. And I'm having pretty big issues trying to make cmake happy. It's still complaining about lack of pthreads library... which obviously is present because it's part of glibc.

/usr/bin/ld: cannot find -lpthreads

Tried to google for that and cmake but there are various unrelated issues around cmake... 
But I'm still working on it. Just FYI that I'm debugging cmake stuff which is new territory for me ;)

**Comment by thestr4ng3r** [comment]
Ok, that is a bit strange indeed.
This is the place where my cmake files add pthreads as a dependency:
https://github.com/thestr4ng3r/chiaki/blob/master/lib/CMakeLists.txt#L98-L99
which is just the standard way to do this in cmake:
https://cmake.org/cmake/help/latest/module/FindThreads.html
What is often good in such cases is to pass `-DCMAKE_VERBOSE_MAKEFILE=ON` to cmake to see exactly what commands the Makefile runs so you can narrow down the issue.

**Comment by fenio** [comment]
Well for testing purposes I created the most simple CMakeLists.txt:

cmake_minimum_required (VERSION 2.8.7)
find_package(Threads)

And it finds pthreads without issue. But in many various threads around internet I'm finding info that very often cmake reports problem with pthreads while the actual reason is totally different and it complains about other dependency... it's just doing it in very unfriendly way since I'm having difficulties finding what's missing. 
I was experimenting with various ways to make cmake more verbose but well... it still says mostly it can't link simple program using -lpthreads.
As I mentioned several times I'm new to cmake but well at least I'm learning something now ;)

**Comment by fenio** [comment]
And the fix was to add nanopb to dependencies. 
You can try yourself to see how funny cmake behaves when it's missing ;)
It says something about third-party nanopb directory and some issues with it but I thought it's not related since log and error files were mentioning only issues with linking with pthread.

Anyway... happily I found the issue. Now need to get rid of too much dependencies as I was adding various stuff trying to find what's missing but that should be easy. I expect upload of package today. In 2-3 hours or so.

**Comment by fenio** [comment]
Ok so from my side I'm ready (just last minute changes left) to upload package to Debian.
Are you going to release new version or should I use 1.3.0+<whatever was committed after that>?

**Comment by fenio** [comment]
Ok nevermind. I've just uploaded what I had. At least ftp-masters counter has started.
My package is based on repo with the commit from 9 hours ago.
https://github.com/thestr4ng3r/chiaki/commit/6e055d307124b370a98179333fc6cc195ec1fef9
We'll see how it goes. From technical perspective it should be fine. I'm working on Debian packages for 20 years or so. The only blocker might be legal issues.
@thestr4ng3r thanks a lot for robust answers and fixes that were needed to make it done
and of course thanks a lot for chiaki in the first place :)

**Comment by fenio** [comment]
inary:chiaki is NEW.
binary:chiaki is NEW.
source:chiaki is NEW.

Your package has been put into the NEW queue, which requires manual action
from the ftpteam to process. The upload was otherwise valid (it had a good
OpenPGP signature and file hashes are valid), so please be patient.

Packages are routinely processed through to the archive, and do feel
free to browse the NEW queue[1].

If there is an issue with the upload, you will receive an email from a
member of the ftpteam.

If you have any questions, you may reply to this email.

[1]: https://ftp-master.debian.org/new.html
     or https://ftp-master.debian.org/backports-new.html for *-backports

**Comment by thestr4ng3r** [comment]
Nice, thanks! My plan is to do a bigger release soon since I recently merged the Nintendo Switch port which should get a few adjustments and I generally release all ports simultaneously so packaging 6e055d3 for now should be good.

**Comment by fenio** [comment]
Holy shit... none of my packages ever got accepted SO quickly.

chiaki_1.3.0+6e055d3-1_amd64.changes ACCEPTED into unstable, unstable

So chiaki is now available in official Debian archive.

**Comment by thestr4ng3r** [comment]
Nice! Thanks for your work.

I think we can close this issue now. While this is of course only for Debian and the original issue seems to speak more about generic deb packages for multiple distributions, I don't think generic debs make much sense since they have to (or should) link against system libraries.

**Comment by fenio** [comment]
Just FYI that chiaki migrated to Debian testing/bullseye.
https://packages.debian.org/search?keywords=chiaki
