### ISSUE TITLE
I couldn't find R1-R2 -L1-L2 buttons on PC-Keyboard

### ISSUE THREAD

**Issue by TalaChartShiraz** [thestr4ng3r/chiaki#206]
Hi guys...
I am using Chiaki for writing a game test. It works very well. I can control my game with PC-keyboard. I could find Right, Left, Down, Up directions by using Arrow keys. Also, I found Cross, Trigale, Square and Circle buttons on my PC-Keyboard. But unfortunately, I couldn't find  R1-R2-L1 and L2 buttons on my PC-Keyboard. Could anyone help me?
Thanks in advance.

**Comment by TalaChartShiraz** [comment]
Hi again, guys...
Nobody can help me? (I am talking with u Florian  ;) ). Honestly, I need to find any solution to solve my issue.
BR,
Alireza

**Comment by thestr4ng3r** [comment]
What OS are you using? A more recent windows build with configurable keybindings is here: https://ci.appveyor.com/project/thestr4ng3r/chiaki/builds/31405306/artifacts
On Linux and macOS the easiest solution will be to build it yourself or wait until the next release since the current one does not expose the shoulder buttons to the keyboard.
