### ISSUE TITLE
Where is console information saves

### ISSUE THREAD

**Issue by rock6663** [thestr4ng3r/chiaki#225]
i need to find register saves of my console from chiaki but i cant find them on my pc where are these files (i will copy files to my phone for playing from my phone i haven't got monitor)

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
