### ISSUE TITLE
[question]Where is files of saved console(account id consol id etc.)

### ISSUE THREAD

**Issue by rock6663** [thestr4ng3r/chiaki#228]
where can i find files of saved console (im asking for windows and android)
For example you can find files of saved consoles for sony's remote play from this path
path:C:\Users\{username}\AppData\Local\Sony Corporation\PS4 Remote Play
where is these files for chiaki i wanna export my console's remote play files directly to my phone i dont have monitor so i cant register my phone directly

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.

**Comment by rock6663** [comment]
is this a bot how is this not understood this is just a simple question i am asking save path #225 as you can see i opened this question twice i explained more clearly this time there is no way that is not understandable

**Comment by thestr4ng3r** [comment]
Read the comment and do what it says.
