### ISSUE TITLE
Local area network

### ISSUE THREAD

**Issue by seisdr** [thestr4ng3r/chiaki#229]
It would be so useful for me that if I can use my ps4 anywhere without having an internet access just establishing  wifi on my android so can you implement that please?
https://github.com/MysteryDash/Offline-PS4-Remote-Play

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
