### ISSUE TITLE
Chiaki v1.2.0 : Linux eoan , Unknown session request error

### ISSUE THREAD

**Issue by fckgtr** [thestr4ng3r/chiaki#238]
I'm running linux eoan 19 on desktop computer 
I'm using AppImage v1.2.0 downloaded from chiaki releases
All about remote connexion setting on PS4 has been set (i'm using Official remote play PS4 from my macbook laptop and it's works very well) 

I've follow instruction , and i managed to add my PS4 successful but , when i'm trying to launch connexion i have an error "Chiaki Session has quit : Unknown Session Request Error" 

I've activated log verbose , so i only have this dump : 
```
==> /home/franck/.local/share/Chiaki/Chiaki/log/chiaki_session_2020-05-19_08-39-37-295295.log <==
[2020-05-19 08:39:37:295295] [I] Logging to file /home/franck/.local/share/Chiaki/Chiaki/log/chiaki_session_2020-05-19_08-39-37-295295.log
[2020-05-19 08:39:37:295295] [I] Chiaki Version 1.2.0
[2020-05-19 08:39:37:341341] [I] Starting session request
[2020-05-19 08:39:37:347347] [E] Session request connect failed eventually.
[2020-05-19 08:39:37:348348] [I] Session has quit
[2020-05-19 08:39:37:349349] [I] OpenGL initialized with version "4.5 (Core Profile) Mesa 19.2.8"
```
I don't understand why it doesn't work , any helps will be appreciate 

Thanks a lot

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
