### ISSUE TITLE
How to use Chiaki from outside the network?

### ISSUE THREAD

**Issue by s3v3ns3v3n** [thestr4ng3r/chiaki#241]
Hi, did anyone try to make this work remotely from outside the network where the PS4 is located. Without going too far (home VPN server) I was wondering if it was possible to use dyndns set on router with the right open ports to play remotely? If you managed to do that, would you be so kind to share a semi-step by step guide of how you achieved it?

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
