### ISSUE TITLE
 avcodec_get_hw_config failed on win 10 1903 x64 

### ISSUE THREAD

**Issue by maxinhmm** [thestr4ng3r/chiaki#245]
when i try to use vaapi option on windows 10 i get this error message :
Failed to initialize Stream Session: avcodec_get_hw_config failed
swapping gpu didnt help

**Comment by benkhouya** [comment]
Same here, using chiaki 1.2.1 on windows 10 (x64) build 2004 and nvidia gtx 1070

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
