### ISSUE TITLE
How can I use chiaki to stream but play on ps4 with controller?

### ISSUE THREAD

**Issue by ptronic** [thestr4ng3r/chiaki#255]
Android

When I connect the controller to the ps4 it disconnects my session, can I play normally and have chiaki just mirror the screen?

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
