### ISSUE TITLE
Play with the controller connected to the ps4 while chiaki is running

### ISSUE THREAD

**Issue by ptronic** [thestr4ng3r/chiaki#256]
**What platform does your feature request apply to?**
Choose one or more: Both

**Is your feature request related to a problem? Please describe.**
When I connect the controller to the ps4 chiaki shutdown the session

**Describe the solution you'd like**
I would like to be able to play with the controller connected to the ps4 while chiaki is running

**Comment by Amanuense-del-diavolo** [comment]
I don't think it possible since the PS4 doesn't allow it, (I have to try, but I'm pretty shure the connection would be closed even using the original app for the remote play), If you need to reduce the latency I'll suggest to use the video output from the ps4 hdmi to see the screen and to connect the controller trought chiaki, it's the best way to reduce latency, since the biggest part of it is due to the encoding/decoding of the video signal, a better explanation of why you'r tryng to use that specific setup my help giving you a better advice

**Comment by grill2010** [comment]
This is not possible, the PS4 is closing the connection and not chiaki. If you want to connect your Dualshock controller to your PS4 while you are connected with chiaki you have to have at least a second PS4 profile and instead of choosing then your main profile when you connect the controller you have to choose the second profile. Then the PS4 will not close the connection and you will be able to use the Dualshock controller connected to your PS4.

**Comment by independentcod** [comment]
As grill2010 mentioned, this is exactly what I do and it works, but you cannot get to go on your other account, server will close again

**Comment by ptronic** [comment]
I was able to make it work with 2 accounts but somehow it wouldn't work with my main account. What's happening?

**Comment by ptronic** [comment]
Can I stream my main account? Or maybe make save games shared between accounts

**Comment by grill2010** [comment]
What exactly was not clear with "this is not possible, the PS4 is closing the connection and not chiaki"? If you choose your main account when you connect your Dualshock controller the PS4 will disconnect chiaki. There is no way around that, it's a limitation which is coming from the PS4 itself. Chiaki can't change that. If you connect your controller to your second account it's registered with that account and you will not be able to control your main account as far as I know. Why do you not just connect the controller to chiaki?

**Comment by ptronic** [comment]
What's the difference between accounts? Why does it work on the 2nd one but not the first?

**Comment by grill2010** [comment]
You have to ask Sony why they decided to handle it that way. In general when you connect via chiaki or any other Remote Play application the PS4 will treat it like a controller, which means your PS4 has already a controller connected to your account when you are using chiaki. If you now decide to connect a real controller to the account which is already used by a remote play client the PS4 thinks now that you want to terminate the remote play session and use a real controller instead. It's that simple and there is no way a program or an app can change that behavior as this is just how the PS4 itself will handle this.

**Comment by Amanuense-del-diavolo** [comment]
> What's the difference between accounts? Why does it work on the 2nd one but not the first?

the reason why it's not working with the second account is because you have to set a session for every account you wish to use on every console, the pairing is account dependant, not account independant, so if you wish to connect with a second account you need  to remove the connection to the first account and re-pair the console with the second account, and then you should be able to play from the console with the first account and see it with chaki with the second account.

**Comment by thestr4ng3r** [comment]
Closing because this is something we can't change. Thanks to @grill2010 for explaining the reasons and the workaround!
