### ISSUE TITLE
Request: Auto-Build script

### ISSUE THREAD

**Issue by independentcod** [thestr4ng3r/chiaki#258]
**What platform does your feature request apply to?**
Choose one or more: Desktop/Android/Both/... ALL

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] NO

**Describe the solution you'd like**
A clear and concise description of what you want to happen. configure and build chiaki automatically with ffmpeg feature

**Describe alternatives you've considered**
https://github.com/independentcod/Chiaki-AutoCompile

**Additional context**

#!/usr/bin/bash
sudo apt-get install cmake ffmpeg. h264. qt5-default qttools5-dev-tools libqt5svg5-dev qtmultimedia5-dev opus. libproto. protobuf. -y;
git clone https://github.com/thestr4ng3r/chiaki.git --recursive;
cd chiaki;
cmake . && make -j8 && sudo make install;
echo 'All Done!';
chiaki;

This is what I've done tell me if something is missing

**Comment by hacker-lc** [comment]
Before creating your own script, please be advised that there is already a Travis CI instructions, which should be clear enough for compiling your own build in Linux platform. 

https://github.com/thestr4ng3r/chiaki/blob/master/.travis.yml

**Comment by thestr4ng3r** [comment]
Such build scripts have two major problems: Firstly, they are always specific to a single distribution or environment or need complex distribution detection and logic to figure out what packages to install and how, making them impractical to maintain.
Secondly, they hide away many options such as where to place the build directory or what optional features to enable.
So overall my experience with scripts like this is that they confuse users and produce errors rather than help them, so the only way to build chiaki with this repository alone will stay to call cmake directly, which is the best compromise between ease of use, maintainability and available options. 
However if you have any distribution-specific tips, feel free to add them to https://github.com/thestr4ng3r/chiaki/blob/master/doc/platform-build.md.
