### ISSUE TITLE
`morning` command line argument

### ISSUE THREAD

**Issue by keymandll** [thestr4ng3r/chiaki#264]
Hi!

First of all, thanks for the amazing work. I just wanted to ask if anyone knows what the `morning` command line argument is and where should the value be obtained from?

Thanks in advance.

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
