### ISSUE TITLE
Can't get chiaki to compile on mac

### ISSUE THREAD

**Issue by KmanProdz** [thestr4ng3r/chiaki#271]
On my attempt to compile using the given instructions, I eventually after a few seconds get this: 

"-- Checking for module 'libudev'
--   No package 'libudev' found
-- Could NOT find Udev (missing: Udev_LIBRARIES) (found version "")
-- Checking for module 'libevdev'
--   No package 'libevdev' found
-- Could NOT find Evdev (missing: Evdev_LIBRARIES) (found version "")
-- Setsu disabled
CMake Error at gui/CMakeLists.txt:5 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "CMakeOutput.log"."

I can not find libudev, libevdev online to install for Mac and I'm therefore unsure how to go about this. Thanks

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
