### ISSUE TITLE
PS5 Support

### ISSUE THREAD

**Issue by mixalis1987** [thestr4ng3r/chiaki#280]
**What platform does your feature request apply to?**
Desktop / Linux

**Is your feature request related to a problem? Please describe.**
This is not a problem but more on the line of information request.

**Describe the solution you'd like**
Do you think it will be easy to make chiaki work with PS5 and do you have plans to try and make it compatible with the PS5?

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by grill2010** [comment]
How should anyone be able to answer that now?
Could be that Sony is not changing much so that it will still work on PS5. Maybe just some minor changes. Could also be possible that the PS5 Remote Play protocol is completely different (little bit unlikely though but possible). It could even be that they are going to change the protocol for the PS4 and the PS5 the same way which means it will not work anymore neither for the PS4 or the PS5.

Everything is possible and all we can do is to wait and hope it will still work for PS4 and only small changes would be needed to fix it.

**Comment by mixalis1987** [comment]
Hmm maybe I wasn't very clear. What I really wanted to know is if the
developer has plans to attempt to make it compatible, when the console
comes out. He might not have the time etc to bother with it.

**Comment by thestr4ng3r** [comment]
If the protocol stays similar enough, there is no reason not to support the PS5.

**Comment by dogtopus** [comment]
Seems that PS5 is already supported in the official PS4 remote play app. So maybe the protocol will be similar enough
