### ISSUE TITLE
Wired XBOX 360 Controller Issue

### ISSUE THREAD

**Issue by crl0901** [thestr4ng3r/chiaki#285]
I'm not really sure how to troubleshoot this issue.  I got Chiaki up and running and it was using my wired 360 controller fine.  I used evtest to figure out what buttons were mapped to what, and configured them in my Chiaki.conf file.  It was working beautifully this morning.  Now when I fired it up and attempted to play, it doesn't recognize any of my controller buttons, even those evtest still shows it working.  I had to close out Steam initially to get it working earlier, but that little trick isn't working this time around.  Here are my mappings that worked previously:
[keymap]
box=BTN_NORTH
cross=BTN_SOUTH
d-pad_down=BTN_TRIGGER_HAPPY4
d-pad_left=BTN_TRIGGER_HAPPY1
d-pad_right=BTN_TRIGGER_HAPPY2
d-pad_up=BTN_TRIGGER_HAPPY3
l1=BTN_TL
l2=ABS_RY
l3=BTN_THUMBL
left_stick_down=S
left_stick_left=S
left_stick_right=S
left_stick_up=S
moon=BTN_EAST
options=BTN_START
ps=BTN_MODE
pyramid=BTN_WEST
r1=BTN_TR
r2=ABS_RZ
r3=BTN_THUMBR
right_stick_down=F
right_stick_left=Left
right_stick_right=G
right_stick_up=F

**Comment by crl0901** [comment]
An update: This morning I powered on the PS4, powered on my Linux PC, closed Steam, started Chiaki and everything worked fine. Played for about an hour and then the stream froze.  Closed out my Chiaki window, opened it again and got an error message saying there was already a remote play stream going.

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
