### ISSUE TITLE
Long Distance Multiplayer Connection Advice

### ISSUE THREAD

**Issue by fuhrog** [thestr4ng3r/chiaki#290]
Hi all!  I'll just start this off by saying I am unsure if this is even possible within the realms of this program, but I wanted to give it a shot anyway.  What I am attempting to do is play co-op ps4 games on pc with a friend from several states away.  I am under the impression this cannot be achieved using only chiaki, and that I would have to stream chiaki on the program Parsec and invite my friend through there.  After connecting, they would be able to assume the player 2 position on an alternate psn account of mine and a second controller connected to my ps4.  This, however, is not what has occurred in our many attempts.

I can successfully use chiaki for remote play when playing alone.  But when trying to connect my friend's chiaki to my ps4, they receive this error:

[I] Regist starting search
[I] Regist sending search packet
[E] Regist timed out waiting for search response
[E] Regist search failed

I gave them the host, base64 psn id (for my alt account), and pin.  On my console registration, I have the broadcasting box checked, although I'm not sure what it means.  Even with them unable to access my ps4, I tried to stream chiaki on Parsec.  They could view my game, but were unable play (we tried this with a player 2 controller/character already in game and without it).  We have both allowed chiaki permission through the firewall, so there shouldn't be an issue there.  So my questions are:

Is it possible to accomplish this with chiaki, or would it only be possible if we were closer?
If so, is what we've been trying completely wrong and what exactly are we doing wrong?
Is Parsec actually necessary for this to work?
And finally, is there some easier way of doing this that I've been overlooking?

Please note that I have absolutely no knowledge of python of coding at all (since I've seen it come up in responses to other posts).
Thank you in advance for your replies!

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
