### ISSUE TITLE
Controller key bindings aren't correct for the Oculus Quest

### ISSUE THREAD

**Issue by doscrash** [thestr4ng3r/chiaki#294]
I installed Chiaki on the Oculus Quest and paired a PS4 controller to it. Surprisingly, it almost worked well! 

However, the button bindings are off on the gamepad. While the two thumbsticks, d-pad, L2 and R2 are correct, the other buttons are wrong.

The Circle button on the gamepad triggers the PS button
The Square button on the gamepad triggers the Cross button
The Triangle button the gamepad triggers Circle button
The Share and Option buttons  on the gamepad don't work at all

Does anyone know how to fix the bindings?

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
