### ISSUE TITLE
2 console, same ip but different account

### ISSUE THREAD

**Issue by shingetsu00** [thestr4ng3r/chiaki#295]
Hello,  I would like to connect the console twice with the same ip but login with two different accounts.
From what I was able to understand to change account just login and use the pin of the remote, however if I login with one account it overwrites the other, is it possible to keep both? I tried to edit registry key but I can only duplicate the consoles, 
I can't create two separate consoles.
Thanks

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
