### ISSUE TITLE
PSN account id // request has no attribute auth

### ISSUE THREAD

**Issue by AlexFubar55** [thestr4ng3r/chiaki#297]
Not sure if I'm in the right place to ask this, but I'm having some troubles getting my account ID, I run the code in termux, I'm able to get it to run and when I paste in the redirect URL, instead of showing me my account id it sends back " requesting 0auth token
Traceback (most recent call last):
   File "./psn-account-id.py" line 79, in <module>
        Api_auth = requests.auth.HTTPBasicAuth(client_ID,   CLIENT_SECRET)
Attribute error: module 'requests' has no attribute  'auth' 

From here I have no idea how to fix the issue if that's on my end and I'm missing a module or its the code, if anyone can help it'd be appreciated

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
