### ISSUE TITLE
cant start stream Failed to initialize Stream Session: Failed to create hwdevice context

### ISSUE THREAD

**Issue by Techman69** [thestr4ng3r/chiaki#306]
i use linux mint with gnome shell
on my hp laptop with core i5 and amd r5 gpu every thing works fine but when connect to my ps4 it gives me this  
'Failed to initialize Stream Session: Failed to create hwdevice context

![error](https://user-images.githubusercontent.com/70453403/91647097-e0556000-ea56-11ea-8f78-285e2e5ca5a5.png)

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
