### ISSUE TITLE
Network support?

### ISSUE THREAD

**Issue by TacoRaptor67** [thestr4ng3r/chiaki#31]
Is this able to connect over the network? Or is it just over local connections? I tried connecting and it told me "Regist search failed".

**Comment by thestr4ng3r** [comment]
What do you mean by network? The sole purpose of this project is to connect over a network.
Please post the entire log here, otherwise I can't know what the problem is.

**Comment by TacoRaptor67** [comment]
Sorry.. maybe network wasn't the best way to put it. Can it connect to my friends PS4 Pro over the internet? I tried inputting his public IP, my username, and the PIN shown on the PS4 but it shows 
`[I] Regist starting search
[I] Regist sending search packet
[E] Regist timed out waiting for search response
[E] Regist search failed`
and there are no logs in the /.local/share/Chiaki/Chiaki/log/ directory.

**Comment by thestr4ng3r** [comment]
Yes, connecting over the internet is possible if you forward the ports 9295 (TCP), 9296 (UDP) and 9297 (UDP). However for the registration I would recommend to do it over the local network since it only has to be done once.

Discovery and Wakeup would theoretically be possible through the internet too if you forward 987 (UDP), but I would highly recommend NOT to do this for now because the way Sony designed it makes trivial replay attacks possible.
