### ISSUE TITLE
Chiaki freezes after 1.5 hours of gaming (Windows 10)

### ISSUE THREAD

**Issue by Pedrinhojean21** [thestr4ng3r/chiaki#311]
I have this problem, sometimes as soon as it locks I close everything and open it again and it works for another hour, but sometimes after it freezes, it doesn't come back, even restarting the ps4 and the pc, he says that  remote play is in use, I would like to know if you have any solution for this?

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
