### ISSUE TITLE
Android 10 DS4 touch pad issue

### ISSUE THREAD

**Issue by amducious** [thestr4ng3r/chiaki#315]
When using the dual shock 4 controller via Bluetooth the touch pad is recognized as a mouse pad with a left click. Because of this some games are not playable without the on screen buttons. This is fine if the phone is close to me but I play with the phone hooked up to a TV. A quick and dirty fix for this may be to give an option for an on screen button that is only the touch pad but have it cover the entire play screen.

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
