### ISSUE TITLE
Help with powershell commands?

### ISSUE THREAD

**Issue by ajslayer** [thestr4ng3r/chiaki#316]
Hello, i apologize for not getting this, but could someone please tell me what commands i need to input into powershell to get the psn-account-id.py script working? currently trying to find my account id number with it. thanks for reading

**Comment by ajslayer** [comment]
wow, i got it. please close this issue. between command prompt and windows terminal, i was trying to figure out what command to input and i tried powershell and it worked. sorry about that lol

**Comment by ajslayer** [comment]
i dl'd python but i guess i wasnt copy and pasting it right. i ended up downloading the github desktop app, cloning the chiaki repo, and opening the python file in the github dt app lol. it opened python and ran the script automatically

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
