### ISSUE TITLE
Chaiki over 4g

### ISSUE THREAD

**Issue by MajorasMaks** [thestr4ng3r/chiaki#318]
I'm trying to get chiaki to work over 4g, it works fine with my wifi but I wanted to use it when I'm not at home as well. I have forwarded the ports: 9295 TCP and UDP, 9296 UDP, 9297 UDP and 987 UDP, on IPv4 only. I have set my wifi IP as the host in chiaki but it just keeps loading forever and than shows an error message. I've seen other posts about this but no-one seems to have found a solution. My router is Fritz Box 7490. Thanks in advance.

**Comment by troy896** [comment]
You have to use your public IP, not your WiFi ip. Also forward 9303 udp, with all those forwarded you should be fine.

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
