### ISSUE TITLE
Chiaki over 4g

### ISSUE THREAD

**Issue by MajorasMaks** [thestr4ng3r/chiaki#319]
I'm trying to get chiaki to work over 4g on my galaxy s8, it works fine with my wifi but I wanted to use it when I'm not at home as well. I have forwarded the ports: 9295 TCP and UDP, 9296 UDP, 9297 UDP, 987 UDP and UDP 9303, on IPv4 only. I have set my wifi IP as the host in chiaki but it just keeps loading forever and than shows an error message. I've seen other posts about this but no-one seems to have found a solution. Thanks in advance.

Screenshot of the error message:
 
![Screenshot_20200929-185355_Chiaki.jpg](https://user-images.githubusercontent.com/63014619/94589236-53840900-0285-11eb-8a0a-2d8d9d6ab1d6.jpg)

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
