### ISSUE TITLE
Read Only

### ISSUE THREAD

**Issue by Pedrinhojean21** [thestr4ng3r/chiaki#321]
I would like a little help, I know that you will visualize this so I will speak, CHIAKI is perfect until the moment it sabotages itself with exactly one hour and twenty-three minutes, after that I need to close and when trying to open it the error that a remote process is already being done, with that I get in trouble, as I am starting in the game streaming world, I get lost in my lives, I already had to close a live due to this problem, after a lot of information given, so I realized the goal of CHIAKI and to bring to the LINUX universe this possibility of playing using remote play, since it officially doesn’t, I wanted to know if you have to somehow change the behavior of sony’s official Remote Play, because CHIAKI runs smooth all games without dropping frames, since the official version I have a lot of fps losses, I don't know what the magic is in CHIAKI, but as his problem is that for some time he closes, I wanted to make the official Remote Play with the performance from CHIAKI, you is very smart so what you say will be important. Sorry about that, but I wanted to make lives without defects, I have no resources at the moment for a capture card. I know this is going to end because you don't respect its rules, but the focus of what I'm describing is something that only you can see.

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.

**Comment by Pedrinhojean21** [comment]
you didn't even read what I said.  Complicated.

**Comment by thestr4ng3r** [comment]
You didn't read this:
```
<!-- IF YOU DO NOT USE THE TEMPLATE BELOW, YOUR ISSUE WILL BE CLOSED! THIS APPLIES FOR BUG REPORTS AND FEATURE REQUESTS, NO EXCEPTIONS!
```
