### ISSUE TITLE
Need help with AppVeyor Build

### ISSUE THREAD

**Issue by Ant857** [thestr4ng3r/chiaki#323]
I'm trying to build chiaki using appveyor, but I am completely lost. It doesn't run through the included appveyor script at all. It just finishes within a second or two and says Discovering tests...ok and then build succeeded. If someone can please provide a short explanation or tutorial on how to build chiaki with appveyor that would be very much appreciated as I've been trying for about a week and still can't wrap my head around it.

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
