### ISSUE TITLE
Session request connect failed eventually on ubuntu 20.04

### ISSUE THREAD

**Issue by glonerr** [thestr4ng3r/chiaki#324]
hi 
when i ran chiaki on ubuntu 20.04,it gave me Session request connect failed eventually error. 
when running code getnameinfo(sa, (socklen_t)ai->ai_addrlen, session->connect_info.hostname, sizeof(session->connect_info.hostname), NULL, 0, 0);
it gave me getnameinfo: Temporary failure in name resolution error
the android version ran flawless.
i am a newbee here, can you help me on it?
thanks

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.
