### ISSUE TITLE
Where in the code should I start looking if I want to hook up some hardware video decode to this on the Raspberry

### ISSUE THREAD

**Issue by Fredrum** [thestr4ng3r/chiaki#351]
I'd like to start experimenting with trying to get HW decode working for this on my Raspberry.
Where is a good point to look in the Chiaki code to figure out how to hook something in?
Just experimentally?

**Comment by thestr4ng3r** [comment]
Check out the last commit where a new hw decoder was added: https://github.com/thestr4ng3r/chiaki/commit/1b05f071323e77540bc92e515d3dea38aead7890
And this is the place where the decoder is eventually set up: https://github.com/thestr4ng3r/chiaki/blob/master/gui/src/videodecoder.cpp#L40-L66
I am not a huge fan of this hard-coded static list of possible decoders though. I think it should be possible to just query all the decoders that are available from ffmpeg so all of them will be available without having to add them by hand.

In the future, please respect the GitHub issue template that the text box is pre-filled with here. I am generally quite strict about directly closing issues that don't follow it since otherwise the issue tracker gets filled with a lot of low-quality issues. I am also thinking about providing a better way to ask questions since I don't want GitHub issues to be like a forum, but only for reporting bugs and requesting concrete features.

**Comment by Fredrum** [comment]
Thank you ill start taking a look and see. I think i'll have to start with making sure ffmpeg is using pi hardware decoding and then see. Ive been interested in learning about the pi's mmal anyway but it seems quite complicated and un documented so itll be tricky.

Sorry about the form thing. I felt it wasnt a bug report or a feature request so wasnt sure how to be able to ask the question. Like you're pointing out.

**Comment by thestr4ng3r** [comment]
I've just created Telegram and IRC channels for Chiaki, feel free to join:

- **Telegram:** https://t.me/chiakitg
- **IRC:** #chiaki on irc.freenode.net
