### ISSUE TITLE
Desktop: key mapping to trackpad left/right side click

### ISSUE THREAD

**Issue by lowerzero** [thestr4ng3r/chiaki#365]
It would be good to have ability to click or eather left or right side of trackpad using keyboard

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.

If you do not have a concrete feature request or bug to report, but only a question, you may want to join one of the Chiaki channels and ask there:

- **Telegram:** https://t.me/chiakitg
- **IRC:** #chiaki on irc.freenode.net
