### ISSUE TITLE
Chiaki on linux doesn't work with PS5

### ISSUE THREAD

**Issue by tausciam** [thestr4ng3r/chiaki#369]
I got the PS5 on launch day (obviously) and tried Chiaki 1.3.0. I've used Chiaki before on a PS4 so I had my PSN acct ID and knew how to use it. 

It doesn't see my PS5, so I try to manually add it. I use its IP address in Host. I pasted my account ID in the appropriate spot, put the PS5 into link device and copied the PIN into the spot for the PIN. This is the verbose log

[V] Regist formatted request header:
[V] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[V]      0 50 4f 53 54 20 2f 73 69 65 2f 70 73 34 2f 72 70 POST./sie/ps4/rp
[V]     10 2f 73 65 73 73 2f 72 67 73 74 20 48 54 54 50 2f /sess/rgst.HTTP/
[V]     20 31 2e 31 0d 0a 20 48 54 54 50 2f 31 2e 31 0d 0a 1.1...HTTP/1.1..
[V]     30 48 4f 53 54 3a 20 31 30 2e 30 2e 32 2e 31 35 0d HOST:.10.0.2.15.
[V]     40 0a 55 73 65 72 2d 41 67 65 6e 74 3a 20 72 65 6d .User-Agent:.rem
[V]     50 6f 74 65 70 6c 61 79 20 57 69 6e 64 6f 77 73 0d oteplay.Windows.
[V]     60 0a 43 6f 6e 6e 65 63 74 69 6f 6e 3a 20 63 6c 6f .Connection:.clo
[V]     70 73 65 0d 0a 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 se..Content-Leng
[V]     80 74 68 3a 20 35 38 37 0d 0a 52 50 2d 56 65 72 73 th:.587..RP-Vers
[V]     90 69 6f 6e 3a 20 31 30 2e 30 0d 0a 0d 0a          ion:.10.0....   
[I] Regist starting search
[I] Regist sending search packet
[E] Regist timed out waiting for search response
[E] Regist search failed

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.

If you do not have a concrete feature request or bug to report, but only a question, you may want to join one of the Chiaki channels and ask there:

- **Telegram:** https://t.me/chiakitg
- **IRC:** #chiaki on irc.freenode.net
