### ISSUE TITLE
CHİAKİ PS4 BLACK SCREEN

### ISSUE THREAD

**Issue by kratosdeniz** [thestr4ng3r/chiaki#386]
Hi first, my English is bad, I am a Turk, I wanted to start using the Chiaki remote play application, I got my psn account ID and registration pin or something I registered my ps4 console I am using Windows 10 anyway, after I press the console sign 2 times, a black screen comes out after 10 seconds, the application closes automatically My PlayStation 4 Version is 8.00 and I use the Chiaki 1.3.0 Version, ie the latest version, but the black screen comes off and turns off, so it does not connect to ps4, I use windows 10 I have 4 gb ram and my computer is 12 years old, what is the cause and solution of the black screen problem?

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.

If you do not have a concrete feature request or bug to report, but only a question, you may want to join one of the Chiaki channels and ask there:

- **Telegram:** https://t.me/chiakitg
- **IRC:** #chiaki on irc.freenode.net
