### ISSUE TITLE
WİNDOWS 10 CHİAKİ SİYAH EKRAN

### ISSUE THREAD

**Issue by kratosdeniz** [thestr4ng3r/chiaki#389]
i have a computer with 4 gb ram my operating system windows 10 chiaki i registered the console psn i got my account id or something anyway i registered the console i am trying to connect to the console comes a black screen then it turns itself off

below are photos of this problem

![Ekran Görüntüsü (9)_LI](https://user-images.githubusercontent.com/74663674/100517410-66d72600-319b-11eb-8ba2-79a0ea22fce6.jpg)

![Ekran Görüntüsü (10)](https://user-images.githubusercontent.com/74663674/100517413-69d21680-319b-11eb-95ab-8ac3cb99dc73.png)

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.

If you do not have a concrete feature request or bug to report, but only a question, you may want to join one of the Chiaki channels and ask there:

- **Telegram:** https://t.me/chiakitg
- **IRC:** #chiaki on irc.freenode.net
