### ISSUE TITLE
RPI / linux config file for resolution / hotkeys?

### ISSUE THREAD

**Issue by domb84** [thestr4ng3r/chiaki#396]
I've managed to build this on RetroPie and put together a quick guide here..

https://dominicbird.com/knowledge-base-2/emulation/compile-chiaki-and-add-as-a-custom-port-to-retropie.

However, I can't seem to find any documented options for chiaki at all. Am I missing something form the readme? It took a lot of digging just to find the -platform options.

Are there any documented options for setting the resolution using a config file or hotkeys? F11 has no effect on RPi understandably as I'm not launching from a desktop OS. However I can't even find a away to quit the application without killing it as yet.

If anyone has any hints on where to find the config / hotkeys / in-app docs that would be great.

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.

If you do not have a concrete feature request or bug to report, but only a question, you may want to join one of the Chiaki channels and ask there:

- **Telegram:** https://t.me/chiakitg
- **IRC:** #chiaki on irc.freenode.net
