### ISSUE TITLE
qtaudio_wasapi.dll doesn't work

### ISSUE THREAD

**Issue by CHFreezer** [thestr4ng3r/chiaki#399]
OS: windows 10 20h2
chiaki: 1.3.0
PS4 firmware: 8.00

I follow #1 delete qtaudio_windows.dll will be no sound or get crackling audio.
1.2.1 can work for me, but my ps4 has been updated to 8.0 firmware.

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.

If you do not have a concrete feature request or bug to report, but only a question, you may want to join one of the Chiaki channels and ask there:

- **Telegram:** https://t.me/chiakitg
- **IRC:** #chiaki on irc.freenode.net
