### ISSUE TITLE
Chiaki does not recognize gamepad on Ubuntu 20.04

### ISSUE THREAD

**Issue by lggregorio** [thestr4ng3r/chiaki#400]
Hello there,
I am running Chiaki on Ubuntu 20.04.1 with minimal install (no extra software) and no matter what I do, I am not able to make it to recognize my gamepad Logitech F310.
I have tried installing Chiaki through Snap Store and also tried the Appimage but when I try to map the gamepad buttons, they are not captured, it only reads my keyboard entries.
I have tested my gamepad using "jstest-gtk" and it is recognizable, also I have no issues on PS2 emulator PCSX2.
Is there anything I am missing here?

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.

If you do not have a concrete feature request or bug to report, but only a question, you may want to join one of the Chiaki channels and ask there:

- **Telegram:** https://t.me/chiakitg
- **IRC:** #chiaki on irc.freenode.net
