### ISSUE TITLE
WINDOWS 10 CHIAKI SHUTS OFF WITH BLACK SCREEN

### ISSUE THREAD

**Issue by kratosdeniz2** [thestr4ng3r/chiaki#403]
**Environment**
 - OS/Distribution: 
 - Desktop Environment: 
 - Hardware: 
 - Exact Version or Commit Hash and Installation Method: 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Log Files**
If your issue is about Registration or Streaming, you MUST attach a log file of a session that showed your issue here.
Do not enable Verbose Logging unless explicitly told to.
On desktop, you can see the directory that log files are written to in the Settings under "Log Directory".
On Android, go into Settings -> Session Logs and export one from there.

**Screenshots**
![Ekran Görüntüsü (10)](https://user-images.githubusercontent.com/76163597/102690790-f27f2800-4218-11eb-8f0f-df179f53491e.png)

**Additional context**
Hi, I downloaded the chiaki application for windows 10, my playstation 4 version is 8.03, I got my account ID so I successfully connected my ps4 game console. Chiaki turns off and gives a black screen when connecting to ps4. What is the reason above?

**Comment by thestr4ng3r** [comment]
Your issue has been closed due to not correctly following the issue template. Feel free to open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow.

If you do not have a concrete feature request or bug to report, but only a question, you may want to join one of the Chiaki channels and ask there:

- **Telegram:** https://t.me/chiakitg
- **IRC:** #chiaki on irc.freenode.net
